repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-merge-conflict
    - id: detect-private-key
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-added-large-files      # <— đổi từ forbid-large-files thành cái này
      args: ['--maxkb=5000']           # chặn file > 5MB
