name: 'order_to_delivery'
version: '1.0.0'
config-version: 2

profile: 'order_to_delivery'   # trùng với tên trong profiles.yml

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # nơi dbt build
clean-targets:
  - "target"
  - "dbt_packages"
